apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: 719129114745.dkr.ecr.us-east-1.amazonaws.com/conduit:803bc908361e56b1cee195a6910b0a8986715c17
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: api-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - name: http
      port: 80
      targetPort: 3000
