apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: api-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@conduit-postgres.cun8ggsywmqg.us-east-1.rds.amazonaws.com:5432/conduit?schema=public"
        JWT_SECRET: "{{ .jwtSecret }}"
  dataFrom:
    - extract:
        key: "arn:aws:secretsmanager:us-east-1:719129114745:secret:rds!db-bc8ad49b-77bc-4175-b14f-c5013a5935e2-rgR3YD"
  data:
    - secretKey: jwtSecret
      remoteRef:
        key: conduit/jwt-secret
